### ISSUE TITLE
dobi a tool for automating docker tasks

### ISSUE THREAD

**Issue by dnephin** [Teradata/docker-images#31]
Hello, 

I'm following up on https://github.com/docker/cli/issues/267 opened by @ebd2. You may be interested in [dobi](https://dnephin.github.io/dobi/) a project I've been working on to automate docker build tasks.

There's an example of building and tagging multiple images here: https://github.com/dnephin/dobi/blob/master/examples/tag-images/dobi.yaml

Using that example you could extend it with the following config to also push multiple images:

```yaml
alias=push-images:
    tasks: ['app:push', 'db:push']
    description: "Push all the images"
```

Let me know if you have any questions or feedback about the project.

Feel free to close this issue at any time if you are not interested.
